# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import datetime
import uuid


@dataclasses.dataclass()
class User:
    id: uuid.UUID
    name: str
    age: int
    created_at: datetime.datetime | None
    updated_at: datetime.datetime | None
